export enum MutationTypes {
  CHANGE_LEFT_DRAWER = 'CHANGE_LEFT_DRAWER',
  SHOW_HEADER_SHADOW = 'SHOW_HEADER_SHADOW',
  CHANGE_RIGHT_DRAWER = 'CHANGE_RIGHT_DRAWER',
  CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE',
  CHANGE_PROGRESS_BAR_PERCENT = 'CHANGE_PROGRESS_BAR_PERCENT',
  SHOW_PROGRESS_BAR = 'SHOW_PROGRESS_BAR',
}
